app = 'cipherly'
primary_region = 'ewr'
swap_size_mb = 1024

[env]
NODE_OPTIONS = '--max-old-space-size=4096'
SITE_URL = "https://cipherly.dev"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
